test:
	go test -v -cover

cover:
	go test -v -coverprofile=cover.out
	go tool cover -html=cover.out -o cover.html
	@start "" "C:\Users\Ivan\go\src\github.com\ivansevryukov1995\golang_web_services_course\4\cover.html"
	